config/routes.rb
Jilli::Application.routes.draw do
  get 'journal_entries/search'
  resources :journal_entries

  get 'patient_profiles/search'
  resources :patient_profiles

  get 'flash_cards/search'
  get 'flash_cards/next'
  get 'flash_cards/prev'
  resources :flash_cards

  root :to => 'application#index'

end

app/models/journal_entry.rb
require 'simple_search'

class JournalEntry < ActiveRecord::Base
  extend SimpleSearch
end

app/controllers/journal_entries_controller.rb
class JournalEntriesController < ApplicationController
  # GET /journal_entries
  # GET /journal_entries.xml
  def index
    @journal_entries = JournalEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @journal_entries } 
      format.xml  { render :xml => @journal_entries }
    end
  end

  # GET /journal_entries/1
  # GET /journal_entries/1.xml
  def show
    @journal_entry = JournalEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @journal_entry }
      format.xml  { render :xml => @journal_entry }
    end
  end

  # GET /journal_entries/new
  # GET /journal_entries/new.xml
  def new
    @journal_entry = JournalEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @journal_entry }
      format.xml  { render :xml => @journal_entry }
    end
  end

  # GET /journal_entries/1/edit
  def edit
    @journal_entry = JournalEntry.find(params[:id])
  end

  # POST /journal_entries
  # POST /journal_entries.xml
  def create
    @journal_entry = JournalEntry.new(params[:journal_entry])

    respond_to do |format|
      if @journal_entry.save
        format.html { redirect_to(@journal_entry, :notice => 'Journal entry was successfully created.') }
        format.json { render :json => @journal_entry, :status => :created, :location => @journal_entry }
        format.xml  { render :xml => @journal_entry, :status => :created, :location => @journal_entry }
      else
        format.html { render :action => "new" }
        format.json { render :json => @journal_entry.errors, :status => :unprocessable_entity }
        format.xml  { render :xml => @journal_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /journal_entries/1
  # PUT /journal_entries/1.xml
  def update
    @journal_entry = JournalEntry.find(params[:id])

    respond_to do |format|
      if @journal_entry.update_attributes(params[:journal_entry])
        format.html { redirect_to(@journal_entry, :notice => 'Journal entry was successfully updated.') }
        format.json { render :json => [] }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @journal_entry.errors, :status => :uncprocessable_entity }
        format.xml  { render :xml => @journal_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /journal_entries/1
  # DELETE /journal_entries/1.xml
  def destroy
    @journal_entry = JournalEntry.find(params[:id])
    @journal_entry.destroy

    respond_to do |format|
      format.html { redirect_to(journal_entries_url) }
      format.json { render :json => [] }
      format.xml  { head :ok }
    end
  end

  # GET /journal_entries/search
  # GET /journal_entries/search.xml
  def search
    @journal_entries = JournalEntry.search(params[:query])
    @summary_array = @journal_entries.collect do |entry|
      { :text => entry.text, :id => entry.id }
    end

    respond_to do |format|
      format.json { render :json => @summary_array }
    end
  end
end

app/helpers/journal_entries_helper.rb
module JournalEntriesHelper
end

app/views/journal_entries/_form.html.erb
<%= form_for(@journal_entry) do |f| %>
  <% if @journal_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@journal_entry.errors.count, "error") %> prohibited this journal_entry from being saved:</h2>

      <ul>
      <% @journal_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/journal_entries/edit.html.erb
<h1>Editing journal_entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @journal_entry %> |
<%= link_to 'Back', journal_entries_path %>

app/views/journal_entries/index.html.erb
<h1>Listing journal_entries</h1>

<table>
  <tr>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @journal_entries.each do |journal_entry| %>
  <tr>
    <td><%= journal_entry.text %></td>
    <td><%= link_to 'Show', journal_entry %></td>
    <td><%= link_to 'Edit', edit_journal_entry_path(journal_entry) %></td>
    <td><%= link_to 'Destroy', journal_entry, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Journal entry', new_journal_entry_path %>

app/views/journal_entries/new.html.erb
<h1>New journal_entry</h1>

<%= render 'form' %>

<%= link_to 'Back', journal_entries_path %>

app/views/journal_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @journal_entry.text %>
</p>


<%= link_to 'Edit', edit_journal_entry_path(@journal_entry) %> |
<%= link_to 'Back', journal_entries_path %>