config/routes.rb
Jilli::Application.routes.draw do
  get 'journal_entries/search'
  resources :journal_entries

  get 'patient_profiles/search'
  resources :patient_profiles

  get 'flash_cards/search'
  get 'flash_cards/next'
  get 'flash_cards/prev'
  resources :flash_cards

  root :to => 'application#index'

end

app/models/flash_card.rb
require 'simple_search'

class FlashCard < ActiveRecord::Base
	extend SimpleSearch
end

app/controllers/flash_cards_controller.rb
class FlashCardsController < ApplicationController
  # GET /flash_cards
  # GET /flash_cards.xml
  def index
    @flash_cards = FlashCard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @flash_cards }
      format.xml  { render :xml => @flash_cards }
    end
  end

  # GET /flash_cards/1
  # GET /flash_cards/1.xml
  def show
    @flash_card = FlashCard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @flash_card }
      format.xml  { render :xml => @flash_card }
    end
  end

  # GET /flash_cards/new
  # GET /flash_cards/new.xml
  def new
    @flash_card = FlashCard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @flash_card }
      format.xml  { render :xml => @flash_card }
    end
  end

  # GET /flash_cards/1/edit
  def edit
    @flash_card = FlashCard.find(params[:id])
  end

  # POST /flash_cards
  # POST /flash_cards.xml
  def create
    @flash_card = FlashCard.new(params[:flash_card])

    respond_to do |format|
      if @flash_card.save
        format.html { redirect_to(@flash_card, :notice => 'Flash card was successfully created.') }
        format.json { render :json => @flash_card, :status => :created, :location => @flash_card }
        format.xml  { render :xml => @flash_card, :status => :created, :location => @flash_card }
      else
        format.html { render :action => "new" }
        format.json { render :json => @flash_card.errors, :status => :unprocessable_entity }
        format.xml  { render :xml => @flash_card.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /flash_cards/1
  # PUT /flash_cards/1.xml
  def update
    @flash_card = FlashCard.find(params[:id])

    respond_to do |format|
      if @flash_card.update_attributes(params[:flash_card])
        format.html { redirect_to(@flash_card, :notice => 'Flash card was successfully updated.') }
        format.json { render :json => [] }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @flash_card.errors, :status => :unprocessable_entity }
        format.xml  { render :xml => @flash_card.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /flash_cards/1
  # DELETE /flash_cards/1.xml
  def destroy
    @flash_card = FlashCard.find(params[:id])
    @flash_card.destroy

    respond_to do |format|
      format.html { redirect_to(flash_cards_url) }
      format.json { render :json => [] }
      format.xml  { head :ok }
    end
  end

  # GET /flash_cards/search
  # GET /flash_cards/search.xml
  def search
    @flash_cards = FlashCard.search(params[:query])
    @summary_array = @flash_cards.collect do |card|
      { :text => card.front, :id => card.id }
    end

    respond_to do |format|
      format.json { render :json => @summary_array }
    end
  end

  # GET /flash_cards/aext
  # GET /flash_cards/next.xml
  def next
    params[:topic] ||= ''
    @flash_cards = FlashCard.find(
      :all,
      :conditions => ["lower(topic) = ?", params[:topic].downcase],
      :order => :id
    )
    found = false
    @flash_card = @flash_cards.detect do |item|
      if found
        next true 
      elsif item.id.to_s == params[:id] 
        found = true
      end
      false 
    end || @flash_cards.first

    respond_to do |format|
      format.json { render :json => @flash_card }
    end
  end

  # GET /flash_cards/prev
  # GET /flash_cards/prev.xml
  def prev
    params[:topic] ||= ''
    @flash_cards = FlashCard.find(
      :all,
      :conditions => ["lower(topic) = ?", params[:topic].downcase],
      :order => :id
    )
    @flash_card = nil
    @flash_cards.detect do |item|
        if item.id.to_s == params[:id]
            next true
        end
        @flash_card = item
        false
    end
    @flash_card ||= @flash_cards.last
    
    respond_to do |format|
        format.json { render :json => @flash_card }
    end
  end
end

app/helpers/flash_cards_helper.rb
module FlashCardsHelper
end

app/views/flash_cards/_form.html.erb
<%= form_for(@flash_card) do |f| %>
  <% if @flash_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flash_card.errors.count, "error") %> prohibited this flash_card from being saved:</h2>

      <ul>
      <% @flash_card.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :front %><br />
    <%= f.text_area :front %>
  </div>
  <div class="field">
    <%= f.label :back %><br />
    <%= f.text_area :back %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flash_cards/edit.html.erb
<h1>Editing flash_card</h1>

<%= render 'form' %>

<%= link_to 'Show', @flash_card %> |
<%= link_to 'Back', flash_cards_path %>

app/views/flash_cards/index.html.erb
<h1>Listing flash_cards</h1>

<table>
  <tr>
    <th>Front</th>
    <th>Back</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @flash_cards.each do |flash_card| %>
  <tr>
    <td><%= flash_card.front %></td>
    <td><%= flash_card.back %></td>
    <td><%= link_to 'Show', flash_card %></td>
    <td><%= link_to 'Edit', edit_flash_card_path(flash_card) %></td>
    <td><%= link_to 'Destroy', flash_card, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Flash card', new_flash_card_path %>

app/views/flash_cards/new.html.erb
<h1>New flash_card</h1>

<%= render 'form' %>

<%= link_to 'Back', flash_cards_path %>

app/views/flash_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Front:</b>
  <%= @flash_card.front %>
</p>

<p>
  <b>Back:</b>
  <%= @flash_card.back %>
</p>


<%= link_to 'Edit', edit_flash_card_path(@flash_card) %> |
<%= link_to 'Back', flash_cards_path %>